### PR TITLE
Update core implementation to be compatible with new API

### PR DESCRIPTION
**Pull request by rothn**
On 2024-01-26, I noticed that my window AC had stopped working with voice commands. Upon investigation, it appeared that the underlying API had changed. These changes fix the frigidaire library to be compatible with the new API, while deviating as little as possible from the previous Python API.

I tested this in a Jupyter notebook and with Homeassistant through https://github.com/rothn/frigidaire_homeassistant. Note that I've temporarily embedded this the homeassistant plugin because I was not able to make Homeassistant work with a git requirement. I would like to depend on this model again once the fix hits PYPI.

### CODE REVIEW

**Review by bm1549 — APPROVED** [review]
Appreciate the quick resolution here!

**Comment by bm1549** [comment]
Released in 0.18.14

**Comment by bm1549** [comment]
@rothn fixed the publish - it's now released via [0.18.15](https://pypi.org/project/frigidaire/0.18.15/)

**Comment by bm1549** [comment]
Just added it to the home-assistant plugin via https://github.com/bm1549/home-assistant-frigidaire/pull/45

**Comment by bm1549** [comment]
Realized there were some breaking changes and reverted the PR via https://github.com/bm1549/home-assistant-frigidaire/pull/46

I noticed you had the fixes in https://github.com/rothn/frigidaire_homeassistant/pull/2 - do you want to apply those to https://github.com/bm1549/home-assistant-frigidaire as well?

**Comment by rothn** [comment]
Happy to do so-- I was not aware there was an actively-maintained plugin based on this code.

**Comment by rothn** [comment]
Created https://github.com/bm1549/home-assistant-frigidaire/pull/47 per our discussion here @bm1549

**Pull request merged**
