### PR TITLE
Fix API calls not working by updating request headers and API base url

### PR DESCRIPTION
**Pull request by DevGary**
Can you test if this fixes it? I don't have the setup to test HASS Components. I tried to make the custom component use my fork by editing the `manifest.json` with 

```
  "requirements": [
    "git+https://github.com/devgary/frigidaire.git@main#frigidaire"
  ],
```

as described [here](https://community.home-assistant.io/t/install-requirement-from-development-fork/571094) but it doesnt work.

Also i'd do a thorough review on the code changes as I don't know Python.

### CODE REVIEW

**Comment by amaisano** [comment]
I tested in Postman but got the same `401` -- "message: Unauthorized".

Here is my Postman setup - maybe it's wrong?

POST https://api.latam.ecp.electrolux.com/authentication/authenticate

Headers:
```
session_token:
x-ibm-client-id:Gsdwexj38r1sXSXIPVdxj4DGoU5ZoaI6aW6ZckBI
user-agent:Frigidaire/81 CFNetwork/1206 Darwin/20.1.0
content-type:application/json
accept:*/*
accept-language:en-us
authorization:Basic Gsdwexj38r1sXSXIPVdxj4DGoU5ZoaI6aW6ZckBI
```

Body:
```json
{
    "username": "x@y.z",
    "password": "mypassword",
    "deviceId": "mycustomdeviceid",
    "brand": "Frigidaire",
    "country": "US"
}
```

**Comment by DevGary** [comment]
I guess the POST url needs to be https://api.us.ecp.electrolux.com/authentication/authenticate. I changed that locally on my end since I am in Canada but forgot to include that in the PR. Also you need the header `x-api-key` which should be set to the same as `x-ibm-client-id`

**Comment by amaisano** [comment]
works!

```json
{
    "status": "OK",
    "code": "ECP0000",
    "message": "success",
    "data": {
        "sessionKey": "redacted"
    }
}
```

**Comment by amaisan0** [comment]
We really need a way to specify our region per install. Can we abstract that value to a variable like username or password?

**Review by bm1549 — APPROVED** [review]
Thanks for the fix here!

**Comment by bm1549** [comment]
Closes #17

**Comment by pman193** [comment]
Tried to make the changes but file permissions don't let me. I tried to make the changes to the Frigidaire.js file. I'm not a coder but I can copy and paste with the best of them. Was wondering if anyone could update the original plugin or create a new one with the changes.

**Comment by bm1549** [comment]
@pman193 there is no JS files in this repo. Could you clarify what your request here is?

**Comment by pman193** [comment]
Hey. I was referring to the original Homebridge Frigidaire plugin. I was using your finds to edit the frigidaire.js plugin. The new updated Frigidaire app broke the plugin.

**Comment by amaisano** [comment]
@pman193 the PR I opened should work for the homebridge plugin... maybe. if your tests didn't work with the changes I made please comment on that PR and request changes. It's tricky with dependencies - your plugin might be using a cached version or overwriting when you restart. Let's take the convo over there: https://github.com/karlg100/frigidaire/pull/12

**Pull request merged**
